---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea-act-runner
  name: gitea-act-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-act-runner
  strategy: {}
  template:
    metadata:
      labels:
        app: gitea-act-runner
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: runner
        image: gitea/act_runner:0.3.0@sha256:99f72f5821d44e18dd1fcab86703a79bbdffcdbdc87bb1d4fdb0f0c5495e9777
        imagePullPolicy: IfNotPresent
        #command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- run.sh"]
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: GITEA_INSTANCE_URL
          value: "https://codeberg.org"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-runner-secret
              key: token
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 265Mi
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        - name: gitea-runner-data
          mountPath: /data
      - name: daemon
        image: docker:29.2.1-dind@sha256:68f6d9ab84623d1116c5432a3b924a07ee09960e6129ca1cb03ef14010588cb4
        env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKER_OPTS
          value: "--iptables=false"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 265Mi
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
      volumes:
      - name: gitea-runner-data
        persistentVolumeClaim:
          claimName: gitea-act-runner
      - name: docker-certs
        emptyDir: {}

