---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea-act-runner
  name: gitea-act-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-act-runner
  strategy: {}
  template:
    metadata:
      labels:
        app: gitea-act-runner
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      containers:
      - name: runner
        image: gitea/act_runner:0.4.1@sha256:696a59b51ad3d149521e3beb0229d5fb88f87295e1616f940199793274415b56
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- run.sh"]
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: GITEA_INSTANCE_URL
          value: "https://codeberg.org"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-runner-secret
              key: token
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 265Mi
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        - name: gitea-runner-data
          mountPath: /data
      - name: daemon
        image: docker:29.4.0-dind@sha256:a6dd5322747a95cd8e3207bd8d415a8fd20ec34e9c00f06dc019cbd912013489
        env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKER_OPTS
          value: "--iptables=false"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 265Mi
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
      volumes:
      - name: gitea-runner-data
        persistentVolumeClaim:
          claimName: gitea-act-runner
      - name: docker-certs
        emptyDir: {}

