apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: gitea-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: GITEA_RUNNER_TOKEN