---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker-ci
spec:
  interval: 30m
  chart:
    spec:
      chart: agent
      sourceRef:
        kind: HelmRepository
        name: woodpecker-ci-helm
        namespace: actions
      version: 2.0.1
  valuesFrom:
    - kind: ConfigMap
      name: woodpecker-ci-helm-values