---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  interval: 30m
  values:
    controllers:
      flaresolverr:
        replicas: 0
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsUser: 1000
        containers:
          app:
            image:
              repository:  ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
            env:
              LOG_LEVEL: info
            resources:
              requests:
                cpu: 18m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop:
                  - ALL
    persistence:
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 256Mi
    service:
      app:
        ports:
          http:
            port: 8191