# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: opencode-go-qwen3-8-max
spec:
  modelName: opencode-go/qwen3.8-max
  params:
    model: anthropic/qwen3.8-max
    apiBase: https://opencode.ai/zen/go/v1
    apiKeyRef:
      name: litellm-secret
      key: OPENCODE_GO_API_KEY
    dropParams: true
    additional:
      extra_headers: '{"x-opencode-session": "e0002380-7302-4bb8-ab7b-81ae5c982dcd", "User-Agent": "my-agent/1.0"}'
  info:
    maxInputTokens: 1000000
    maxOutputTokens: 131072
    supportsFunctionCalling: true
    supportsPromptCaching: true
    extra:
      supports_reasoning: true
      supports_vision: true
      input_cost_per_token: 0.000002
      output_cost_per_token: 0.000006
      cache_read_input_token_cost: 0.00000025
      cache_creation_input_token_cost: 0.0000025
