apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: linkding-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: LINKDING_SUPERUSER_NAME
    - secretKey: password
      remoteRef:
        key: LINKDING_SUPERUSER_PASSWORD