---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "mrtb-io"
spec:
  dnsNames:
    - "mrtb.io"
    - "*.mrtb.io"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: hetzner-dns01
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: "mrtb-io-tls"
  usages:
    - digital signature