apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-opnsense
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: external-dns-opnsense-secret
    creationPolicy: Owner
  data:
    - secretKey: api_secret
      remoteRef:
        key: OPNSENSE_API_SECRET
    - secretKey: api_key
      remoteRef:
        key: OPNSENSE_API_KEY
    - secretKey: opnsense_host
      remoteRef:
        key: OPNSENSE_HOST