---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 30m
  values:
    controllers:
      open-webui:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: v0.11.4@sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f
            env:
              # OAuth
              ENABLE_OAUTH_SIGNUP: true
              ENABLE_OAUTH_PERSISTENT_CONFIG: false
              OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
              # Features
              ENABLE_LOGIN_FORM: true
              ENABLE_OLLAMA_API: false
              ENABLE_OPENAI_API: false
              ENABLE_RAG_WEB_SEARCH: true
              ENABLE_SEARCH_QUERY: true
              ENABLE_SIGNUP: true
              # Search
              RAG_WEB_SEARCH_ENGINE: searxng
              SEARXNG_QUERY_URL: http://searxng.workloads.svc.cluster.local:8080/search?q=<query>
              # Websockets
              ENABLE_WEBSOCKET_SUPPORT: true
              WEBSOCKET_MANAGER: redis
              WEBSOCKET_REDIS_URL: redis://open-webui-dragonfly:6379
            envFrom:
              - secretRef:
                  name: open-webui-secret
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    persistence:
      config:
        enabled: true
        existingClaim: open-webui
        globalMounts:
          - path: /app/backend/data
    route:
      app:
        hostnames:
          - chat.mrtb.io
        parentRefs:
          - name: gateway-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: 8080
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist